<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPq00n40\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPq00n40/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPq00n40.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPq00n40\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPq00n40\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pq00n40',
    'container.build_id' => '4225b889',
    'container.build_time' => 1686394523,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPq00n40');
